## Motore di ricerca

In [1]:
import pandas as pd
import numpy as np
import os
from tqdm.notebook import tqdm

In [2]:
folder = "/Users/Flint/Data/recipes/textit"
docids = []
docs = []
for filename in os.listdir(folder):
    if filename.endswith('.txt'):
        docid = filename.replace(".txt", "").split("_")[1]
        docids.append(int(docid))
        with open(os.path.join(folder, filename), 'r') as infile:
            text = infile.read()
            docs.append(text)

### 1. Tokenizzazione

#### Opzione 1: espressioni regolari

In [3]:
from nltk.tokenize import word_tokenize

In [4]:
wt_docs = []
for doc in docs:
    tokens = word_tokenize(doc.lower(), language='italian')
    wt_docs.append(tokens)

#### Opzione 2: tokenizzazione linguistica

In [5]:
import spacy

In [6]:
nlp = spacy.load('it_core_news_lg')

In [7]:
def spacy_tokenizer(text, skip=None):
    tokens = []
    for token in nlp(text.lower()):
        if skip is not None and token.pos_ in skip:
            pass 
        else:
            tokens.append(token.lemma_)
    return tokens

In [8]:
st_docs = []
for doc in tqdm(docs):
    tokens = spacy_tokenizer(doc.lower(), skip=['ADP', 'CONJ', 'SPACE', 'PUNCT', 'DET'])
    st_docs.append(tokens)

  0%|          | 0/5933 [00:00<?, ?it/s]

### 2. Indicizzazione

In [9]:
from collections import Counter

In [10]:
def indexing(tokenized_docs, index_ids):
    l_index = []
    for tokens in tokenized_docs:
        bow = dict(Counter(tokens).most_common())
        l_index.append(bow)
    I = pd.DataFrame(l_index, index=index_ids).fillna(0).T
    return I

In [11]:
W = indexing(wt_docs, docids)
S = indexing(st_docs, docids)

In [12]:
print(f"tokenizzazione non normalizzata: {W.shape[0]}")
print(f"tokenizzazione normalizzata: {S.shape[0]}")

tokenizzazione non normalizzata: 20753
tokenizzazione normalizzata: 18058

In [13]:
S.head()

,1994,2245,810,4634,4152,2523,4146,3629,2537,5258,...,5241,3630,1027,1033,5255,3624,3142,5533,809,1755
e,9.0,1.0,11.0,6.0,9.0,2.0,5.0,3.0,8.0,3.0,...,7.0,20.0,14.0,7.0,7.0,12.0,1.0,4.0,10.0,6.0
g,6.0,6.0,10.0,4.0,6.0,0.0,8.0,2.0,8.0,7.0,...,4.0,8.0,6.0,4.0,6.0,8.0,3.0,9.0,7.0,4.0
tarallo,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dolce,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
farina,4.0,2.0,7.0,4.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,4.0,0.0,0.0,2.0,3.0,0.0,2.0,0.0,3.0

### 3. Ricerca

In [26]:
q = "uova strapazzate con bacon e olive"
q_tokens = spacy_tokenizer(q, skip=['ADP', 'CONJ', 'SPACE', 'PUNCT', 'DET'])
q_bow = dict(Counter(q_tokens).most_common())
q_bow

{'uovo': 1, 'strapazzato': 1, 'bacon': 1, 'e': 1, 'oliva': 1}

In [34]:
q_vector = []
for token in S.index.values:
    if token in q_bow.keys():
        q_vector.append(q_bow[token])
    else:
        q_vector.append(0)
q_vector = np.array(q_vector)
example = pd.Series(q_vector, index=S.index)
example.sort_values(ascending=False)

e                    1
bacon                1
strapazzato          1
oliva                1
uovo                 1
                    ..
1250                 0
ridue cet ne         0
tagliare ne          0
dapprima             0
gnocchi.preparate    0
Length: 18058, dtype: int64

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
sigma = cosine_similarity(np.array([q_vector]), S.T)

/Users/Flint/.pyenv/versions/nlp/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Users/Flint/.pyenv/versions/nlp/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Users/Flint/.pyenv/versions/nlp/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

In [35]:
ranking = pd.Series(sigma[0], index=S.columns)

In [36]:
ranking.sort_values(ascending=False)

1947    0.534821
3043    0.499185
4717    0.494602
1864    0.456630
798     0.451147
          ...
276     0.000000
2133    0.000000
2559    0.000000
1195    0.000000
4326    0.000000
Length: 5933, dtype: float64

In [37]:
print(f"Query: {q}\n\n")

for d, score in ranking.sort_values(ascending=False).head(10).items():
    did = docids.index(d)
    text = docs[did]
    print(f"Doc: {d} - Punteggio: {score}")
    print(f"Testo: {text}\n")
    print("===================\n")

Query: uova strapazzate con bacon e olive


Doc: 1947 - Punteggio: 0.5348210163719004
Testo: Uova strapazzate
8 di Uova
q.b. di Sale fino
q.b. di Pepe nero
q.b. di Olio extravergine d'oliva
Per preparare le uova strapazzate, per prima cosa rompete le uova in una ciotola, salate poi sbattete leggermente con una frusta a mano: il composto di tuorli e  albumi non dovrà risultare del tutto omogeneo Scaldate un filo d’olio in una padella e versate le uova sbattute all’interno Dopo un paio di minuti a fuoco medio-alto le uova inizieranno a rapprendersi, quindi rompetele con la frusta, una marisa o una forchetta per ottenere l’effetto strapazzato Le uova dovranno risultare piuttosto morbide, non asciutte: ci vorranno circa 1-2 minuti. A questo punto togliete la padella dal fuoco e servite le vostre uova strapazzate

===================

Doc: 3043 - Punteggio: 0.49918452017784476
Testo: Uova alla diavola
6 di Uova
90g di Tonno sott'olio
25g di Acciughe (alici)
25g di Olive nere
2g di Capperi sott'aceto
1 di Peperoncino fresco
1pizzico di Paprika dolce
3g di Prezzemolo
Per preparare le uova alla diavola iniziate dalla preparazione delle Prendete un tegame e versatevi abbondante acqua. Disponete le uova all'interno e portate a bollore cuocendole a fuoco medio per circa 8 minuti. Quando le uova saranno cotte, spegnete il fuoco e estraetele dal tegame aiutandovi con una schiumarola. Ponetele in una ciotola e quindi mettete la ciotola con le uova a raffreddare sotto un getto di acqua fredda Mentre le uova si raffreddano procedete con la preparazione del ripieno piccante delle vostre uova. Prendete un mixer e versatevi le alici ed il tonno Aggiungete quindi anche le olive nere i capperi e una parte del prezzemolo (tenetene un po' da parte per spolverizzare la superficie delle uova) Unite infine nel mixer anche la paprika Azionate il mixer e continuate a tritare gli ingredienti fino a che non avrete ottenuto un composto cremoso Aggiungete poi l’olio che renderà l’impasto ancora più cremoso e consentirà di amalgamare meglio gli ingredienti A questo punto le uova si saranno raffreddate. Procedete a sgusciarle, tagliatele a metà e con un cucchiaino estraete delicatamente i tuorli sodi avendo cura di non rompere le bianche dell’uovo che vi serviranno successivamente. Prendete i tuorli estratti e versateli nel composto Azionate nuovamente il mixer e amalgamate anche uovo e olio per creare un composto omogeneo e privo di grumi Trasferiti quindi il composto così ottenuto in una sac-à-poche Riempite l’incavo della bianca dell’uovo (da cui avete estratto il tuorlo) con la sac-à-poche Ripetete l’operazione per tutte le uova. Spolverate per finire con della paprika

===================

Doc: 4717 - Punteggio: 0.49460173117693546
Testo: Insalata con uova strapazzate
8 di Uova
200g di Prosciutto cotto
180g di Piselli surgelati
100g di Pomodorini datterini
100g di Fagioli cannellini precotti
80g di Insalata misticanza
q.b. di Olio extravergine d'oliva
q.b. di Sale fino
q.b. di Pepe nero
20 di Basilico
30g di Olio extravergine d'oliva
1 di Scorza di limone
½ di Succo di limone
q.b. di Sale fino
4 di Pane casereccio
q.b. di Olio extravergine d'oliva
Per realizzare l’insalata con uova strapazzate, per prima cosa rimuovete i piselli congelati dal freezer e lasciateli a temperatura ambiente per almeno 15 minuti. Nel frattempo preparate le uova strapazzate: rompete le uova in una ciotola, salate e pepate a piacere poi sbattete leggermente con una frusta a mano Cuocete per un paio di minuti a fuoco medio-alto fino a quando le uova inizieranno a rapprendersi, quindi rompetele con la frusta, una marisa o una forchetta per ottenere l’effetto strapazzato Le uova dovranno risultare ancora morbide ma non asciutte Togliete la padella dal fuoco, trasferite le uova strapazzate in un contenitore e tenete da parte Riducete il prosciutto cotto a cubetti Quando si saranno dorati trasferite i cubetti in una ciotola e tenete da parte.Versate i piselli nella stessa padella che avete utilizzato per il prosciutto, aggiungendo se necessario un altro filo d’olio e cuocete per pochi minuti avendo cura di non farli sfaldare Tenete da parte anche i piselli e tagliate i pomodorini a metà, dopo averli precedentemente lavati Infine preparate la citronette al basilico: lavate e asciugate le foglie di basilico, poi mettetele in un contenitore insieme all’olio Condite il dressing con sale A questo punto siete pronti per assemblare la vostra insalata: versate la misticanza in una ciotola capiente e unite i piselli i fagioli cannellini i pomodorini e il prosciutto cotto Aggiungete anche le uova strapazzate

===================

Doc: 1864 - Punteggio: 0.45662965113740955
Testo: Uova alla coque
4 di Uova
Per preparare le uova alla coque, disponete le uova nel pentolino (assicurandovi di usare uova freschissime e integre) Considerate che la temperatura dell'uovo e la dimensione può incidere sui minuti di cottura: si calcolano 3 minuti dal bollore per uova di dimensioni medie e fredde di frigo; 2 minuti di bollore al massimo per uova a temperatura ambiente.Una volta pronte, scolatele con delicatezza e poggiatele sul portauovo; quindi battete delicatamente con un cucchiaino sulla parte alta dell'uovo Quindi servite le vostre uova alla coque accompagnandole con croccanti crostini di pane

===================

Doc: 798 - Punteggio: 0.4511469482381474
Testo: Olive all' ascolana
1kg di Olive Ascolane tenere
100g di Manzo
100g di Maiale
100g di Pollo
30g di Pane
½ di Cipolle
q.b. di Noce moscata
80g di Parmigiano Reggiano DOP
½ di Scorza di limone
1pizzico di Chiodi di garofano macinati
1 di Carote
1 di Sedano
1 di Vino bianco
1 di Uova
q.b. di Sale fino
2 di Uova
q.b. di Farina 00
q.b. di Pangrattato
500ml di Olio extravergine d'oliva
Tritate le verdure (cipolla, sedano, carota) e fatele rosolare con 3 cucchiai d’olio extravergine d'oliva, tagliate a piccoli dadini i tre tipi di carni e aggiungetele al soffritto (1-2-3);quando le carni saranno rosolate, salate, aggiungete il vino bianco Togliete il composto dal fuoco e lasciatelo raffreddare, quindi successivamente macinatelo un uovo, il parmigiano grattugiato, la mollica di pane ridotta in briciole (7-8), e impastate bene fino ad ottenere un composto morbido ma compatto lasciatelo riposare per una mezz'oretta.Passate ora a  denocciolare le olive: con un coltellino da cucina a lama liscia, tagliate a spirale l’ oliva senza spezzarla partendo dal picciolo, in modo da ottenere una spirale di polpa liberata dal nocciolo. (10-11-12) Idealmente è come se doveste pelare un agrume senza mai staccare la lama del coltello e rompere di conseguenza la buccia.A questo punto riempite le olive con il ripieno ottenuto avendo cura di ridare loro la forma originaria (che ovviamente sarà un po’ più gonfia!). Preparate intanto tre ciotole contenenti separatamente; farina, uova sbattute e pangrattato. Passate ogni oliva prima nella farina, poi nell’uovo sbattuto e per ultimo nel pangrattato e quando saranno tutte pronte lasciatele riposare al fresco per mezz’ora. e poi ripetete l'operazione per dare una seconda impanata in modo da renderle ben croccanti per la frittura.A questo punto, potete friggere le olive all’ascolana in olio extravergine di oliva bollente,

===================

Doc: 5776 - Punteggio: 0.4446160115013827
Testo: Sfoglie alle olive con pomodoro e briciole di feta
12 di Sfoglie alle olive
1 di Cipolle rosse
4 di Olive nere
3 di Pomodorini ciliegino
20g di Feta
q.b. di Olio extravergine d'oliva
q.b. di Sale fino
12 di Basilico
Per preparare le sfoglie alle olive con pomodoro e briciole di feta inziate a sbucciare la cipolla rossa, dividetela a metà e tagliatela a fettine sottili Lavate e asciugate i pomodorini e tagliateli in quarti Sgocciolate le olive e tagliatele a rondelle Infine sbriciolate la feta aiutandovi con le dita Proseguite con un paio di rondelle di olive Completate le vostre sfoglie alle olive con pomodoro e briciole di feta con un filo d'olio, un pizzico di sale e un paio di foglioline di basilico fresco

===================

Doc: 2888 - Punteggio: 0.44280744277004763
Testo: Uova alla greca
100g di Feta
6g di Acciughe sott'olio
8 di Uova
10g di Olive nere Greche
50g di Peperoni rossi
6 di Basilico
10g di Olio extravergine d'oliva
q.b. di Pepe nero
1pizzico di Sale
Per preparare le uova alla greca iniziate lavando e asciugando il peperone Una volta abbrustolito, chiudetelo dentro ad un sacchetto di plastica, oppure in una ciotola coperta con la pellicola trasparente per circa 15 minuti Nel frattempo ponete a bollire 8 uova fino a farle diventare sode (circa 8 minuti) uindi fatele raffreddare, per velocizzare questa operazione scolatele A questo punto sgusciate le uova tagliatele a metà per il lungo Prendete ora la feta e tagliatela in cubetti molto piccoli A questo punto i peperoni si saranno intiepiditi e la pelle verrà via facilmente, quindi spellateli e tagliate anche questi in piccoli cubetti Prendete ora le olive e denocciolatele con l'apposito strumento in mancanza potete comprare quelle già denocciolate.A questo punto prendete una ciotola e unite la feta, i peperoni tagliati a cubetti e i filetti di acciughe tritati il basilico spezzettato e le olive In ultimo aggiungere l'olio d'oliva, il pepe nero e il sale se necessario, poichè il composto è già molto saporito.Amalgamate bene tutti gli ingredienti Quindi riponetele in frigorifero in un contenitore con coperchio per almeno un’ora. Al momento di servirle, adagiate le uova alla greca su di un lettino di colorata insalata mista o insalatina verde

===================

Doc: 2801 - Punteggio: 0.43028229936038165
Testo: Olive schiacciate
850g di Olive verdi
50g di Olio extravergine d'oliva
q.b. di Sale fino
q.b. di Pepe nero
3 di Aglio
1 di Peperoncino fresco
q.b. di Origano
Per realizzare le olive schiacciate, iniziate al mattino perché dovrete cambiare l'acqua di macerazione un paio di volte al giorno, mattina e sera. Prendete dunque le olive verdi fresche (scegliete quelle più polpose e grandi possibilmente), battetele con un batticarne Riponetele in una ciotola ampia e versate l’acqua Fino a ricoprirle completamente Coprite la ciotola con un canovaccio pulito e asciutto e ricopritele ancora con altra acqua corrente appoggiate nuovamente il canovaccio pulito e asciutto e ricopritele ancora con acqua corrente quindi rovesciatele su un canovaccio pulito Trasferite le olive schiacciate in una ciotola, condite con sale, olio di oliva poi sbucciate l'aglio e affettatelo finemente dividete a metà nel senso della lunghezza il peperoncino fresco eliminate i semini interni e tagliatelo a striscioline sottili Completate il condimento con l’aglio, il peperoncino Mescolate per insaporite e servite le vostre olive schiacciate come contorno (o come antipasto se preferite)

===================

Doc: 5005 - Punteggio: 0.4300130725961134
Testo: Paglia e fieno con asparagi e uova
230g di Paglia e Fieno all'uovo
700g di Asparagi
300g di Ricotta vaccina
50g di Grana Padano DOP
4 di Uova
q.b. di Sale fino
q.b. di Pepe nero
q.b. di Noce moscata
q.b. di Olio extravergine d'oliva
q.b. di Grana Padano DOP
Per preparare le tagliatelle paglia e fieno con asparagi e uova iniziate a cuocere le uova in acqua bollente per 8-10 minuti A cottura ultimata freddate le uova sotto acqua fredda corrente e sbucciatele, dividete gli albumi dai tuorli  Nella ciotola di un mixer dotato di lame per frullare ponete la ricotta aromatizzate con la noce moscata grattugiata salate, pepatee frullate tutto per ottenere una crema omogenea Trasferite la crema in una ciotola ampia e incorporate il Grana Padano grattugiato mescolate con un cucchiaio e tenete da parte la crema. Ora occupatevi della cuocete gli asparagi nell’asparagiera In una padella scaldate un filo di olio di oliva e fate saltare gli asparagi a pezzetti per insaporirli qualche minuto poi a cottura ultimata spegnete il fuoco e tenete da parte qualche punta che servirà per guarnire il piatto Ora occupatevi della cottura della pasta:portate a bollore una pentola con abbondante acqua salata e cuocete le tagliatelle paglia e fieno Scolate la pasta e versatela nella padella con gli asparagi, incorporate la crema di ricotta mescolate per insaporire la pasta e per finire condite con una spolverata di Grana Padano grattugiato La vostra pasta paglia e fieno con asparagi e uova è pronta, guarnite i piatti con le punte degli asparagi prima di servire in tavola

===================

Doc: 4885 - Punteggio: 0.41553486128733297
Testo: Portobello ripieni di uova e formaggio
4 di Funghi portobello
4 di Uova
100g di Edamer
q.b. di Olio extravergine d'oliva
1 di Aglio
q.b. di Sale fino
q.b. di Pepe nero
1 di Radicchio
100g di Gherigli di noci
1 di Aglio
q.b. di Olio extravergine d'oliva
Per preparare i portobello ripieni di uova e formaggio iniziamo dalla pulizia dei funghi. Dopo aver eliminato parte del gambo, dove c'è più terreno bisogna grattarlo via dal resto del gambo e dalla cappella. Utilizzate una piccola spazzola o un panno leggermente inumidito. Staccate il gambo dalla calotta, poi scavate leggermente quest'ultima con un cucchiaio e tritate il tutto al coltello. In una padella calda con un filo d'olio e uno spicchio d'aglio sbucciato, versate i funghi sminuzzati e saltateli a fiamma viva per un paio di minuti al massimo regolando di sale e pepe. Una volta pronti togliete l'aglio e lasciate intiepidire. In una ciotola grattugiate il formaggio attraverso i fori grossi, unite poi l’erba cipollina tagliuzzata e mescolate. A questo punto condite l’interno dei funghi con un goccio d’olio, sale e pepe, e poi farciteli con il ripieno preparato. Mettete un foglio di carta da forno in una padella antiaderente e disponete sopra i portobello farciti con la parte ripiena verso l'alto. Rompete, una alla volta, le uova in una ciotolina e fate scivolare nel mezzo di ciascun fungo. Insaporite con sale e pepe e chiudete con il coperchio lasciando cuocere a fuoco medio-alto per qualche minuto o finché l’albume si sarà rappreso. Avete il tempo per lavare le foglie di radicchio, asciugate, tagliate a striscioline e saltate a fuoco vivo per pochi istanti con olio e l’aglio spellato. Disponete l’insalata tiepida nei piatti, aggiungete le noci spezzettate a mano o al coltello e i portobello ripieni di uova e formaggio!

===================

In [33]:
W[1994].sort_values(ascending=False)

di            19.0
e              9.0
,              8.0
per            6.0
un             6.0
              ...
5mm            0.0
23cm           0.0
3cm            0.0
placchette     0.0
emergere       0.0
Name: 1994, Length: 20753, dtype: float64

## TF-IDF

In [44]:
WTF = W / W.sum(axis=0)

In [45]:
WTF.head()

,1994,2245,810,4634,4152,2523,4146,3629,2537,5258,...,5241,3630,1027,1033,5255,3624,3142,5533,809,1755
di,0.073643,0.062147,0.065957,0.103627,0.074074,0.090909,0.089362,0.022901,0.069519,0.065134,...,0.075117,0.063903,0.053299,0.068493,0.059859,0.074074,0.038217,0.077273,0.059091,0.053628
e,0.034884,0.005650,0.023404,0.031088,0.030303,0.022727,0.012766,0.022901,0.042781,0.011494,...,0.032864,0.034542,0.035533,0.031963,0.024648,0.027160,0.006369,0.018182,0.045455,0.018927
",",0.031008,0.062147,0.055319,0.020725,0.013468,0.045455,0.012766,0.030534,0.037433,0.022989,...,0.018779,0.037997,0.027919,0.041096,0.021127,0.032099,0.025478,0.009091,0.013636,0.018927
per,0.023256,0.022599,0.014894,0.031088,0.013468,0.011364,0.025532,0.038168,0.021390,0.015326,...,0.014085,0.015544,0.010152,0.018265,0.024648,0.022222,0.019108,0.013636,0.022727,0.012618
un,0.023256,0.005650,0.012766,0.025907,0.023569,0.022727,0.017021,0.015267,0.005348,0.019157,...,0.018779,0.020725,0.010152,0.013699,0.017606,0.024691,0.000000,0.018182,0.009091,0.022082

In [47]:
WTF[1994].sort_values(ascending=False).head(5)

di     0.073643
e      0.034884
,      0.031008
per    0.023256
un     0.023256
Name: 1994, dtype: float64

In [48]:
DF = WTF > 0
DF

,1994,2245,810,4634,4152,2523,4146,3629,2537,5258,...,5241,3630,1027,1033,5255,3624,3142,5533,809,1755
di,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
e,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
",",True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
per,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
un,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
flambè,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
risottando,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
maggiore.soltanto,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
gnocchi.preparate,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
emergere,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [57]:
IDF = np.log(DF.shape[1] / DF.sum(axis=1))
WIDF = (WTF.T * IDF).T

In [61]:
WIDF[1994].sort_values(ascending=False).head(10)

taralli          0.128078
campani          0.092967
dolci            0.034744
17-20            0.033676
bricioloso.in    0.033676
singolo          0.029417
12-15            0.024751
merenda          0.024044
ricaverete       0.022263
cordoncino       0.022064
Name: 1994, dtype: float64